version: '3'
services:
  web:
    build: .
    volumes:
      - ./:/app
    ports:
      - 1337:1337
    environment:
      COW: vader
      DATABASE_URL: postgresql://moi:biniou@db:5432/cowsay
      REDIS_URL: redis://biniou@redis:6379/0'
    links:
      - db
      - redis
    depends_on:
      - redis
      - db
  db:
    # Documentation about this image here: https://hub.docker.com/_/postgres
    image: postgres:11
    volumes:
      - ./docker/psql:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_USER: moi
      POSTGRES_PASSWORD: biniou
      POSTGRES_DB: cowsay
    ports:
      - 5432:5432
  redis:
    image: redis
    #command: redis-server --requirepass biniou
    ports:
      - 6379:6379
    environment:
      REDIS_PASSWORD: biniou
  # worker:
  #   image: node
  #   working_dir: /app
  #   command: node worker.js
  #   environment:
  #     REDIS_URL: redis://biniou@redis:6379/0'
  #   volumes:
  #     - ./:/app
  #   links:
  #     - redis
  #   depends_on:
  #   - redis
